#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
agent_refine.py — Deterministic agent-style refinements for examx TeX

Features:
- Replace inline TikZ placeholders (from ocr_to_examx) with \input figures/tikz/figNN.tikz
- Create missing TikZ template files alongside the output TeX
- Optionally apply a deterministic JSON/YAML "edit plan" (future extension)

Usage:
  python3 tools/agent_refine.py input.tex output.tex --create-tikz
  python3 tools/agent_refine.py input.tex output.tex --plan plan.json
"""

import argparse
import json
import re
from pathlib import Path
from typing import List, Optional, Tuple

try:
    import yaml  # optional
except Exception:
    yaml = None


TIKZ_BLOCK_PATTERN = re.compile(
    r"\\begin\{center\}\s*\n\\begin\{tikzpicture\}[\\s\\S]*?% IMAGE_TODO: (?P<path>[^\n]+)[\\s\\S]*?\\end\{tikzpicture\}\s*\n\\end\{center\}",
    re.MULTILINE,
)


def load_plan(plan_path: Optional[Path]):
    if not plan_path:
        return None
    text = plan_path.read_text(encoding="utf-8")
    try:
        return json.loads(text)
    except Exception:
        if yaml is None:
            raise
        return yaml.safe_load(text)


def ensure_tikz_dir(out_tex: Path) -> Path:
    tikz_dir = out_tex.parent / "figures" / "tikz"
    tikz_dir.mkdir(parents=True, exist_ok=True)
    return tikz_dir


def next_fig_id(tikz_dir: Path) -> int:
    max_id = 0
    for p in tikz_dir.glob("fig*.tikz"):
        m = re.match(r"fig(\d+)\.tikz$", p.name)
        if m:
            max_id = max(max_id, int(m.group(1)))
    return max_id + 1


def create_tikz_template(tikz_file: Path, source_hint: str):
    content = (
        "% Auto-generated by agent_refine.py\n"
        f"% SOURCE: {source_hint}\n"
        "% TODO: Replace with actual TikZ code derived from the image.\n"
        "\\begin{tikzpicture}[scale=1.05,>=Stealth,line cap=round,line join=round]\n"
        "  % ...\n"
        "\\end{tikzpicture}\n"
    )
    tikz_file.write_text(content, encoding="utf-8")


def replace_tikz_blocks(tex: str, out_tex: Path, create_tikz: bool) -> Tuple[str, List[Path]]:
    r"""Replace inline tikzpicture blocks with \input{figures/tikz/figNN.tikz}."""
    tikz_dir = ensure_tikz_dir(out_tex)
    created: List[Path] = []

    def repl(match):
        nonlocal created
        src_path = match.group("path").strip()
        if create_tikz:
            fig_id = next_fig_id(tikz_dir)
            tikz_file = tikz_dir / f"fig{fig_id:02d}.tikz"
            create_tikz_template(tikz_file, src_path)
            created.append(tikz_file)
            return ("\\begin{center}\n"
                    f"\\input{{figures/tikz/{tikz_file.name}}}\n"
                    "\\end{center}")
        # If not creating files, keep original block
        return match.group(0)

    new_tex = TIKZ_BLOCK_PATTERN.sub(repl, tex)
    return new_tex, created


def apply_plan(tex: str, plan: Optional[dict]) -> str:
    """Apply a deterministic edit plan (simple search/replace list)."""
    if not plan:
        return tex
    for edit in plan.get("edits", []):
        pattern = edit.get("pattern")
        replace = edit.get("replace", "")
        flags = re.MULTILINE | re.DOTALL if edit.get("dotall") else re.MULTILINE
        if pattern is None:
            continue
        tex = re.sub(pattern, replace, tex, flags=flags)
    return tex


def remove_consecutive_duplicate_lines(tex: str, min_length: int = 20) -> str:
    r"""🆕 v1.0.1：移除连续重复的行（保守策略）
    
    问题场景：
    OCR 或 Pandoc 转换有时会产生连续的重复行，例如：
      所以\(a_{n} = 2 \times 4^{n - 1}\)；
      所以\(a_{n} = 2 \times 4^{n - 1}\)；
    
    保守策略：
    1. 只移除完全相同的连续行
    2. 行长度必须大于 min_length（避免误删短行如 "\par"）
    3. 保留第一行，移除后续重复行
    4. 不处理空行和只有空白的行
    
    Args:
        tex: 输入的 LaTeX 文本
        min_length: 最小行长度阈值，短于此长度的行不检测
        
    Returns:
        去除重复行后的文本
    """
    if not tex:
        return tex
    
    lines = tex.split('\n')
    result = []
    prev_line = None
    removed_count = 0
    
    for line in lines:
        stripped = line.strip()
        
        # 空行或只有空白的行：直接保留
        if not stripped:
            result.append(line)
            prev_line = None  # 重置，空行不参与重复检测
            continue
        
        # 太短的行：直接保留（如 \par, \end{...} 等）
        if len(stripped) < min_length:
            result.append(line)
            prev_line = stripped
            continue
        
        # 检查是否与上一行完全相同
        if prev_line and stripped == prev_line:
            # 重复行，跳过
            removed_count += 1
            continue
        
        # 非重复行，保留
        result.append(line)
        prev_line = stripped
    
    if removed_count > 0:
        print(f"  ✅ 移除了 {removed_count} 行重复内容")
    
    return '\n'.join(result)


def main():
    ap = argparse.ArgumentParser(description="Agent-style deterministic refine for examx TeX")
    ap.add_argument("input", help="Input .tex from ocr_to_examx")
    ap.add_argument("output", help="Output .tex after refinement")
    ap.add_argument("--plan", help="JSON/YAML edit plan file", default=None)
    ap.add_argument("--create-tikz", help="Create tikz files and replace placeholders", action="store_true")
    ap.add_argument("--no-dedup", help="Skip duplicate line removal", action="store_true")
    args = ap.parse_args()

    in_tex = Path(args.input)
    out_tex = Path(args.output)
    out_tex.parent.mkdir(parents=True, exist_ok=True)

    tex = in_tex.read_text(encoding="utf-8")

    # Optionally create tikz inputs
    tex, created = replace_tikz_blocks(tex, out_tex, create_tikz=args.create_tikz)

    # 🆕 v1.0.1：移除连续重复行（默认启用）
    if not args.no_dedup:
        tex = remove_consecutive_duplicate_lines(tex)

    # Optionally apply a plan (search/replace style)
    plan = load_plan(Path(args.plan)) if args.plan else None
    tex = apply_plan(tex, plan)

    out_tex.write_text(tex, encoding="utf-8")

    print(f"Refined TeX written: {out_tex}")
    if created:
        print(f"Created {len(created)} tikz template(s) under {created[0].parent}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
